[package]
name = "oracle-tools"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.139"
oracle = "0.5.6"
procfs = "0.14.2"
users = "0.11.0"
